import os
import re

new_jobs = '''
  {
    id: "prj-104",
    title: "Digital Marketing Manager",
    hot: true,
    company: "Shopee Vietnam",
    location: "TP.HCM",
    timeAgo: "1 giờ trước",
    applicantsCount: 45,
    salaryDisplay: "25 – 40 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "SHP",
    category: "recruitment", 
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 25,
    budgetMax: 40,
    description: "Quản lý và thực thi các chiến dịch Digital Marketing trên nền tảng Shopee.",
    skills: ["Google Ads", "Facebook Ads", "SEO", "Analytics", "Content Strategy"],
    postedDate: "Đăng 1 giờ trước",
    timeLeft: "Còn 15 ngày",
    clientName: "Shopee Vietnam",
    clientRating: 4.8,
    clientReviews: 120,
    clientVerified: true,
    clientHireRate: "90%",
    clientMemberSince: "Năm 2015",
    featured: true
  },
  {
    id: "prj-105",
    title: "Senior UI/UX Designer",
    hot: false,
    company: "MoMo Fintech",
    location: "Remote",
    timeAgo: "2 giờ trước",
    applicantsCount: 30,
    salaryDisplay: "30 – 50 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "MOMO",
    category: "design",
    type: "Remote",
    jobType: "Chính thức",
    budgetMin: 30,
    budgetMax: 50,
    description: "Thiết kế trải nghiệm người dùng cho hệ sinh thái siêu ứng dụng MoMo.",
    skills: ["Figma", "UX Research", "Prototyping", "Design System", "Adobe XD"],
    postedDate: "Đăng 2 giờ trước",
    timeLeft: "Còn 10 ngày",
    clientName: "MoMo Fintech",
    clientRating: 4.9,
    clientReviews: 200,
    clientVerified: true,
    clientHireRate: "95%",
    clientMemberSince: "Năm 2014",
    featured: false
  },
  {
    id: "prj-106",
    title: "DevOps & Cloud Engineer",
    hot: true,
    company: "Tiki Corporation",
    location: "TP.HCM",
    timeAgo: "3 giờ trước",
    applicantsCount: 20,
    salaryDisplay: "35 – 60 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "TIKI",
    category: "web-dev",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 35,
    budgetMax: 60,
    description: "Vận hành và tối ưu hệ thống Cloud, đảm bảo tính sẵn sàng cao cho e-commerce.",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Linux"],
    postedDate: "Đăng 3 giờ trước",
    timeLeft: "Còn 12 ngày",
    clientName: "Tiki Corporation",
    clientRating: 4.7,
    clientReviews: 150,
    clientVerified: true,
    clientHireRate: "92%",
    clientMemberSince: "Năm 2012",
    featured: true
  },
  {
    id: "prj-107",
    title: "HR Business Partner",
    hot: false,
    company: "VinFast",
    location: "Hà Nội",
    timeAgo: "4 giờ trước",
    applicantsCount: 15,
    salaryDisplay: "20 – 35 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "VF",
    category: "recruitment",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 20,
    budgetMax: 35,
    description: "Đối tác nhân sự chiến lược cho các khối phòng ban tại VinFast.",
    skills: ["Tuyển dụng", "HRBP", "Luật Lao Động", "Talent Acquisition"],
    postedDate: "Đăng 4 giờ trước",
    timeLeft: "Còn 20 ngày",
    clientName: "VinFast",
    clientRating: 4.6,
    clientReviews: 80,
    clientVerified: true,
    clientHireRate: "88%",
    clientMemberSince: "Năm 2017",
    featured: false
  },
  {
    id: "prj-108",
    title: "Fullstack Node.js Developer",
    hot: true,
    company: "KiotViet",
    location: "Đà Nẵng / Remote",
    timeAgo: "5 giờ trước",
    applicantsCount: 50,
    salaryDisplay: "20 – 40 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "KIOT",
    category: "web-dev",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 20,
    budgetMax: 40,
    description: "Phát triển tính năng mới cho nền tảng quản lý bán hàng KiotViet.",
    skills: ["Node.js", "React", "MongoDB", "REST API", "TypeScript"],
    postedDate: "Đăng 5 giờ trước",
    timeLeft: "Còn 14 ngày",
    clientName: "KiotViet",
    clientRating: 4.8,
    clientReviews: 110,
    clientVerified: true,
    clientHireRate: "94%",
    clientMemberSince: "Năm 2014",
    featured: true
  },
  {
    id: "prj-109",
    title: "Data Engineer",
    hot: false,
    company: "VNPay",
    location: "Hà Nội",
    timeAgo: "6 giờ trước",
    applicantsCount: 25,
    salaryDisplay: "30 – 55 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "VNPAY",
    category: "ai-ml",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 30,
    budgetMax: 55,
    description: "Xây dựng và tối ưu hóa hệ thống Data Pipeline cho hàng triệu giao dịch.",
    skills: ["Apache Spark", "Airflow", "BigQuery", "Python", "dbt"],
    postedDate: "Đăng 6 giờ trước",
    timeLeft: "Còn 18 ngày",
    clientName: "VNPay",
    clientRating: 4.9,
    clientReviews: 190,
    clientVerified: true,
    clientHireRate: "96%",
    clientMemberSince: "Năm 2011",
    featured: false
  },
  {
    id: "prj-110",
    title: "Content Creator & Brand Manager",
    hot: false,
    company: "Grab Vietnam",
    location: "TP.HCM",
    timeAgo: "7 giờ trước",
    applicantsCount: 60,
    salaryDisplay: "18 – 30 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "GRAB",
    category: "design",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 18,
    budgetMax: 30,
    description: "Sáng tạo nội dung và quản lý thương hiệu Grab trên các kênh mạng xã hội.",
    skills: ["Content Marketing", "Copywriting", "Social Media", "Brand Strategy"],
    postedDate: "Đăng 7 giờ trước",
    timeLeft: "Còn 10 ngày",
    clientName: "Grab Vietnam",
    clientRating: 4.7,
    clientReviews: 300,
    clientVerified: true,
    clientHireRate: "93%",
    clientMemberSince: "Năm 2014",
    featured: false
  },
  {
    id: "prj-111",
    title: "Supply Chain Manager",
    hot: true,
    company: "Samsung Vietnam",
    location: "Bắc Ninh",
    timeAgo: "8 giờ trước",
    applicantsCount: 18,
    salaryDisplay: "35 – 65 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "SS",
    category: "recruitment",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 35,
    budgetMax: 65,
    description: "Quản lý chuỗi cung ứng toàn cầu, tối ưu hóa quy trình sản xuất và vận chuyển.",
    skills: ["Quản lý chuỗi cung ứng", "ERP SAP", "Lean Six Sigma", "Procurement"],
    postedDate: "Đăng 8 giờ trước",
    timeLeft: "Còn 25 ngày",
    clientName: "Samsung Vietnam",
    clientRating: 4.8,
    clientReviews: 500,
    clientVerified: true,
    clientHireRate: "98%",
    clientMemberSince: "Năm 2008",
    featured: true
  },
  {
    id: "prj-112",
    title: "QA Engineer (Automation)",
    hot: false,
    company: "Axon Active Vietnam",
    location: "Đà Nẵng",
    timeAgo: "9 giờ trước",
    applicantsCount: 22,
    salaryDisplay: "18 – 35 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "AXON",
    category: "web-dev",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 18,
    budgetMax: 35,
    description: "Phát triển và duy trì framework kiểm thử tự động cho các dự án phần mềm.",
    skills: ["Selenium", "Cypress", "Python", "Postman", "JIRA"],
    postedDate: "Đăng 9 giờ trước",
    timeLeft: "Còn 15 ngày",
    clientName: "Axon Active Vietnam",
    clientRating: 4.6,
    clientReviews: 70,
    clientVerified: true,
    clientHireRate: "91%",
    clientMemberSince: "Năm 2008",
    featured: false
  },
  {
    id: "prj-113",
    title: "Financial Analyst",
    hot: true,
    company: "VPBank Securities",
    location: "Hà Nội",
    timeAgo: "10 giờ trước",
    applicantsCount: 35,
    salaryDisplay: "25 – 45 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "VPBS",
    category: "recruitment",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 25,
    budgetMax: 45,
    description: "Phân tích tài chính, đánh giá rủi ro và tư vấn đầu tư chiến lược.",
    skills: ["Excel", "Python", "Financial Modeling", "Báo Cáo Tài Chính", "CFA"],
    postedDate: "Đăng 10 giờ trước",
    timeLeft: "Còn 14 ngày",
    clientName: "VPBank Securities",
    clientRating: 4.7,
    clientReviews: 95,
    clientVerified: true,
    clientHireRate: "92%",
    clientMemberSince: "Năm 2010",
    featured: true
  },
  {
    id: "prj-114",
    title: "Game Developer (Unity)",
    hot: false,
    company: "VNG Corporation",
    location: "TP.HCM",
    timeAgo: "11 giờ trước",
    applicantsCount: 40,
    salaryDisplay: "28 – 50 triệu/tháng",
    workType: "Toàn thời gian",
    logoType: "VNG",
    category: "mobile-apps",
    type: "Full-Time",
    jobType: "Chính thức",
    budgetMin: 28,
    budgetMax: 50,
    description: "Phát triển game mobile trên nền tảng Unity 3D, tối ưu hóa hiệu năng.",
    skills: ["Unity3D", "C#", "Game Design", "Shader", "Firebase"],
    postedDate: "Đăng 11 giờ trước",
    timeLeft: "Còn 12 ngày",
    clientName: "VNG Corporation",
    clientRating: 4.8,
    clientReviews: 250,
    clientVerified: true,
    clientHireRate: "96%",
    clientMemberSince: "Năm 2004",
    featured: false
  }
'''

with open('js/data.js', 'r', encoding='utf-8') as f:
    content = f.read()
    
# Insert the new jobs before the closing bracket of initialProjects
match = re.search(r'(id: "prj-103",[\s\S]*?\}\n)\];', content)
if match:
    new_content = content[:match.end(1)] + ",\n" + new_jobs + "\n];" + content[match.end():]
    
    # Replace initialCategories
    categories_replacement = '''const initialCategories = [
  { id: "web-dev", name: "Websites, IT & Software", count: 6840 },
  { id: "mobile-apps", name: "Mobile Apps & Devices", count: 3240 },
  { id: "ai-ml", name: "AI, Machine Learning & Data", count: 2450 },
  { id: "recruitment", name: "Direct Recruitment Roles", count: 4120 },
  { id: "design", name: "Design, Media & UI/UX", count: 3800 },
  { id: "writing", name: "Technical Writing & Specs", count: 1250 }
];'''
    new_content = re.sub(r'const initialCategories = \[[\s\S]*?\];', categories_replacement, new_content)
    
    with open('js/data.js', 'w', encoding='utf-8') as f2:
        f2.write(new_content)
    print('js/data.js updated')
else:
    print('Failed to update js/data.js')
